name: miosense
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  video_player: ^2.5.1
  http: ^0.13.3
  socket_io_client: ^2.0.0
  fl_chart: ^0.40.0
  percent_indicator: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\videos\body_cuadriceps_video.mp4
    - assets\videos\isquiotibiales.mp4
    - assets\videos\gemelos.mp4